#!/system/bin/sh

# Disable overlay. NEED FIX!!
( while :
do
    sf=$(service list | grep -c "SurfaceFlinger")

    if [ $sf -eq 1 ]
    then
        service call SurfaceFlinger 1008 i32 1
        break
    else
        sleep 1
    fi
done )&
